import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useState, useEffect } from "react";

export default function Home() {
  const [error, setError] = useState();

  useEffect(() => {
    try {
      const buffer = new SharedArrayBuffer(8);
    } catch (e) {
      setError(e);
    }
    // try once on render
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>{error ? error.message : "its supported"}</p>
        </div>
      </main>
    </>
  );
}
